In [1]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

#Load dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [2]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [3]:
#import the necessary module
from sklearn.model_selection import train_test_split

X=digits.data
Y=digits.target
#split data set into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.35, random_state = 47)

In [4]:
#Create a Decision Tree Classifier (using Gini)
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 47, max_depth=7, min_samples_leaf=10)

clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=47, splitter='best')

In [5]:
# Predict the classes of test data
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[9 6 4 6 5 6 9 6 9 0 4 0 0 4 8 8 4 6 4 2 9 8 0 5 1 3 2 9 7 7 5 5 6 3 8 8 3
 5 1 4 5 6 8 4 9 4 8 9 4 5 8 6 5 5 0 7 6 0 1 9 4 5 8 2 9 7 4 4 2 3 6 3 7 6
 6 3 2 1 2 4 6 6 2 4 0 3 6 3 4 4 4 8 3 6 9 5 7 0 0 4 2 6 1 8 7 9 1 2 9 1 6
 1 1 2 6 9 5 9 0 6 2 8 2 3 5 7 9 0 6 0 9 8 3 5 2 6 0 6 4 2 4 8 3 9 8 1 2 6
 7 6 9 9 1 9 3 8 2 5 8 6 4 7 6 8 6 4 3 3 5 9 0 9 9 7 4 9 4 9 6 3 2 6 6 0 8
 4 5 1 7 2 9 6 4 4 7 0 0 0 7 4 3 9 7 5 1 2 7 4 0 6 6 6 4 6 5 6 4 6 3 6 9 5
 9 8 3 3 5 6 4 6 6 2 6 6 6 0 8 3 0 6 0 8 6 7 1 2 6 4 4 7 5 4 0 4 8 8 8 0 6
 8 0 5 5 6 6 2 7 7 9 4 7 0 5 9 7 3 2 5 5 0 6 9 8 4 8 9 7 7 8 6 9 5 3 0 3 8
 5 2 9 1 8 7 6 3 1 1 2 0 2 8 9 2 8 4 5 8 9 9 6 5 7 8 6 4 1 1 9 8 0 5 2 4 8
 1 9 5 7 8 7 2 9 7 6 8 8 3 3 6 7 4 7 8 3 7 1 6 2 2 4 9 6 6 6 1 0 8 7 6 7 8
 5 5 1 9 2 6 2 8 2 3 6 9 0 2 6 7 9 0 3 5 6 0 2 8 9 5 7 3 5 8 3 3 4 2 3 7 1
 2 8 2 6 0 2 3 1 9 3 5 0 9 6 7 9 8 1 7 6 6 9 0 9 7 6 5 4 3 1 9 1 8 8 8 6 5
 6 3 3 4 9 6 7 0 3 2 1 7 6 0 8 2 5 4 3 1 5 0 6 1 1 6 7 5 9 3 7 0 0 0 4 5 0
 3 0 8 

In [6]:
# Model Accuracy
from sklearn import metrics
print("Confusion Matrix: ", metrics.confusion_matrix(y_test, y_pred))
print ("Accuracy : ", metrics.accuracy_score(y_test,y_pred) * 100)
print("Report : ", metrics.classification_report(y_test, y_pred))


Confusion Matrix:  [[57  0  0  0  3  0  0  0  0  2]
 [ 0 34  1  2  2  1 13  0  1  5]
 [ 1  0 44  2  1  1  7  2  4  1]
 [ 0  0  2 44  0  3  0  1  4  2]
 [ 0  2  0  0 52  5  1  3  1  0]
 [ 0  1  3  0  3 49 14  2  3  3]
 [ 0  0  0  0  1  1 60  1  2  0]
 [ 0  1  3  1  0  2  0 45  2  0]
 [ 0  2  6  3  0  0  0  2 48  4]
 [ 0  0  0  1  0  1  1  2  2 56]]
Accuracy :  77.74244833068363
Report :                precision    recall  f1-score   support

           0       0.98      0.92      0.95        62
           1       0.85      0.58      0.69        59
           2       0.75      0.70      0.72        63
           3       0.83      0.79      0.81        56
           4       0.84      0.81      0.83        64
           5       0.78      0.63      0.70        78
           6       0.62      0.92      0.75        65
           7       0.78      0.83      0.80        54
           8       0.72      0.74      0.73        65
           9       0.77      0.89      0.82        63

    accuracy  